#!/usr/bin/env sh

# This script installs Bitwarden to a system location. It is meant to be used
# via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - $2: The GitHub release tag containing the artifacts to install
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"

########################################
# Input processing
########################################

GITHUB_REPO="$1"
RELEASE_TAG="$2"

########################################
# Main
########################################

# Bitwarden is not available on ARMv7
install_github_release_deb "$GITHUB_REPO" "$RELEASE_TAG" '*amd64.deb'
