#!/usr/bin/env sh

# This script initialized the X11 session.

#######################################
# Qt environment variables
#######################################

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORMTHEME='qt5ct'

#######################################
# Display-specific environment setup
#######################################

autorandr --change --force

#######################################
# Desktop background
#######################################

xsetroot -solid '#131313'
