# This file contains custom configuration options for Lightdm greeters
#
# {{@@ header() @@}}

[greeter]
background = #1C1C1C
cursor-theme-name = {{@@ cursor_theme @@}}
cursor-theme-size = {{@@ cursor_size @@}}
font-name = {{@@ font @@}}
hide-user-image = true
icon-theme-name = {{@@ icon_theme @@}}
theme-name = {{@@ theme @@}}
user-background = false
xft-dpi = {{@@ dpi * 1.5 @@}}
