# This file contains custom configuration options for Lightdm greeters
#
# {{@@ header() @@}}

[greeter]
background = #1C1C1C
theme-name = Adwaita-dark
icon-theme-name = acyl-icon-set
xft-dpi = {{@@ dpi @@}}
user-background = false
hide-user-image = true
