#!/bin/sh

# This script populates /etc/hosts file with most frequently visited remote
# hosts

#######################################
# Variables
#######################################

REMOTE_HOSTS='duckduckgo.com
facebook.com
forum.pokemoncentral.it
github.com
google.com
nonsolomamma.com
messenger.com
ordbogen.dk
pokemonshowdown.com
wiki.pokemoncentral.it'

# Marker for custom remote hosts
REMOTE_HOSTS_MARKER='Custom sites'

#######################################
# Adding remote websites
#######################################

# Line number of the remote hosts marker
REMOTE_LINE="$(grep -n "$REMOTE_HOSTS_MARKER" /etc/hosts | cut -d ':' -f 1)"

# Clearing remote resources entries
REMOTE_LINE=$(( REMOTE_LINE + 2 ))
sed -i "$REMOTE_LINE,\$d" /etc/hosts

# Adding an entry for every remote resource
echo "$REMOTE_HOSTS" | while read HOST; do
	IPS=$(host "$HOST")

    echo "$IPS" | grep 'has address' | tail -n 1 | cut -d ' ' -f 1,4 \
        >> /etc/hosts
    echo "$IPS" | grep 'has IPv6 address' | tail -n 1 | cut -d ' ' -f 1,5 \
        >> /etc/hosts
done

echo 'Remote hosts IPs updated'
