[project]
name = "dotfiles"
version = "0.1.0"
description = "My configuration files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["dotdrop>=1.15.0", "xdg>=6.0.0"]

[dependency-groups]
dev = ["black>=25.1.0", "docopt>=0.6.2", "i3ipc>=2.2.1", "isort>=6.0.0"]
