#!/usr/bin/env sh

# This script installs the Zed text editor to a system location. It is meant to
# be used via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - $2: The GitHub release tag containing the artifacts to install
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"

########################################
# Input processing
########################################

GITHUB_REPO="$1"
RELEASE_TAG="$2"

########################################
# Main
########################################

DEB_GLOB="$(cpu_arch 'amd64' \
    | xargs printf '*%s*%s.deb' "$(lsb_release --codename --short)")"
install_github_release_deb "$GITHUB_REPO" "$RELEASE_TAG" "$DEB_GLOB"

log_debug 'Alias zeditor to zed'
which zeditor | xargs -I '{}' ln --force --symbolic '{}' /usr/local/bin/zed
