#!/usr/bin/env sh

# This script installs Nerd Fonts Symbols to a system location. It is meant to
# be used via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - $2: The GitHub release tag containing the artifacts to install
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"

########################################
# Variables
########################################

SYMBOLS_NERD_FONT_DIR=/usr/local/share/fonts/symbols-nerd-font/

########################################
# Input processing
########################################

GITHUB_REPO="$1"
RELEASE_TAG="$2"

########################################
# Main
########################################

log_debug "Ensure $SYMBOLS_NERD_FONT_DIR exists"
mkdir --parents "$SYMBOLS_NERD_FONT_DIR"

RELEASE_TAR_GLOB='NerdFontsSymbolsOnly.tar.xz'
install_github_release_tar "$GITHUB_REPO" "$RELEASE_TAG" "$RELEASE_TAR_GLOB" \
    '*.ttf' "$SYMBOLS_NERD_FONT_DIR"

log_debug 'Refresh fonts cache...'
fc-cache --force --really-force --system-only --verbose | log_debug
