#!/usr/bin/env sh

# {{@@ header() @@}}

# This script defines shell "dot directories", that is directories where shell
# configuration files (dotfiles) are grouped. The idea was taken from zsh's
# ZDOTDIR

# POSIX shell dot directory
# shellcheck disable=2027,2140
export SDOTDIR="{{@@ sdotdir | home_abs2var @@}}"

# bash dot directory
# shellcheck disable=2027,2140
export BDOTDIR="{{@@ bdotdir | home_abs2var @@}}"

# zsh dot directory
# shellcheck disable=2027,2140
export ZDOTDIR="{{@@ zdotdir | home_abs2var @@}}"
