# This file contains the picom configuration. It is meant to be used with i3
#
# {{@@ header() @@}}

#######################################
# Disable unwanted features
#######################################

# Blur
blur-background = false;
blur-background-fixed = false;
blur-background-frame = false;

# Fading
fading = false;

#######################################
# Shadow
#######################################

shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-radius = 5;

#######################################
# Rules
#######################################

rules = (
    {
        opacity = 0.5;
        opacity-override = false;
    },
    {
        match = "window_type = 'dnd'",
        opacity = 0.7;
        shadow = true;
    },
    {
        match = "window_type = 'dock'",
        opacity = 1;
        shadow = true;
    },
    {
        match = "window_type = 'drowdown_menu' || window_type = 'popup_menu'",
        opacity = 0.92;
        shadow = true;
    },
    {
        match = "window_type = 'notification'",
        opacity = 1;
    }
    {
        match = "window_type = 'tooltip'",
        opacity = 0.95;
        shadow = true;
    },
    {
        match = "focused || group_focused || name = '{{@@ i3_ws_live_tree.marker @@}}'";
        opacity = 1;
    }
)

#######################################
# Misc
#######################################

# The "glx" backend freezes virtual machines
backend = "xrender";
dbe = false;
# False so that same application windows are not active altogether
detect-client-leader = false;
detect-client-opacity = true;
detect-rounded-corners = true;
detect-transient = true;
# True so that replying on Telegram doesn't unfocus the main window
use-ewmh-active-win = true;
# True so that notifications are not displayed over i3lock
unredir-if-possible = true;
vsync = false;
