#!/usr/bin/env sh

# {{@@ header() @@}}

# This is a NetworkManager dispatch script that disables Wi-Fi
# when an Ethernet connection is active and enables it when
# there is no cable connection up.

#######################################
# Functions
#######################################

# This function sets the wireless interface status. and logs to systemd.
#
# Arguments:
#   - $@: Any argument `wifi` accepts
set_wireless() {
    wifi "$@"
    echo "Wireless set $*" | systemd-cat -t 'WIRELESS-CTRL' -p info
}

#######################################
# Wi-Fi management
#######################################

INTERFACE="$1"
ACTION="$2"

case "$INTERFACE" in

    eth*|usb*|en*)
        case "$ACTION" in

            'up')
                set_wireless 'off'
                ;;

            'down')
                set_wireless 'on'
                ;;
        esac
        ;;
esac
