#!/usr/bin/env bash

# This script initializes bash login shells.
# Most of the setup is delegated to bashrc

# {{@@ header() @@}}

#######################################
# Loading configuration paths
#######################################

# shellcheck disable=2027,2140
source "{{@@ shell_dirs_file | home_abs2var @@}}"

#######################################
# Delegating to bashrc
#######################################

source "$BDOTDIR/bashrc"
