#!/usr/bin/env sh

# This script cleans up pacman and yay cache
#
# Parts of this file are an edited version of original from Alberto Redondo:
# https://herbort.me/posts/automatically-cleaning-pacman-and-yay-cache-in-arch-linux/
#
# {{@@ header() @@}}

########################################
# Variables
########################################

YAY_CACHE_DIRS="$(find /home -maxdepth 3 -mindepth 3 -type d \
    -path '*/.cache/yay')"

########################################
# Functions
########################################

# This function removes the whole directory of uninstalled AUR packages from
# the yay caches.
clean_uninstalled_aur_packages() (
    PACMAN_FOREIGN_PACKAGE_NAMES="$(mktemp --tmpdir 'pacman-pack-names.XXXX')"
    UNINSTALLED_AUR_PACKAGE_NAMES="$(mktemp --tmpdir 'aur-pack-names.XXXX')"
    # shellcheck disable=SC2064
    trap "rm --force --recursive \
            $PACMAN_FOREIGN_PACKAGE_NAMES $UNINSTALLED_AUR_PACKAGE_NAMES" \
        EXIT INT HUP TERM

    YAY_BUILD_DIRS="$(yay_build_dirs)"

    pacman --query --quiet --foreign | sort > "$PACMAN_FOREIGN_PACKAGE_NAMES"
    echo "$YAY_BUILD_DIRS" | xargs --no-run-if-empty --max-args 1 basename \
        | sort | comm -2 -3 - \
            "$PACMAN_FOREIGN_PACKAGE_NAMES" > "$UNINSTALLED_AUR_PACKAGE_NAMES"

    # Grep uninstalled package names from absolute paths in YAY_BUILD_DIRS
    echo "$YAY_BUILD_DIRS" | grep --file "$UNINSTALLED_AUR_PACKAGE_NAMES" \
            --fixed-strings \
        | xargs --no-run-if-empty rm --recursive --force
)

# This function returns the upstream sources of old versions of an AUR package
# together with the build output from the last installation. Old versions of
# the package are considered to be the ones that have no pacman tarball in the
# AUR package directory in the yay cache.
#
# Arguments:
#   - $1: The package's yay build directory.
get_old_upstream_sources_and_build() (
    PACKAGE_DIR="$1"

    # The git repository we operate on is the AUR package itself, not the
    # upstream sources. Hence untracked files are from upstream.
    UPSTREAM_SOURCES="$(git -C "${PACKAGE_DIR:?}" ls-files --others \
            --directory --exclude '*.pkg.tar*' \
        | xargs --no-run-if-empty -I '{}' echo "$PACKAGE_DIR/{}")"

    # This relies on the fact that old versions have been removed by paccache
    KEPT_VERSIONS="$(find "$PACKAGE_DIR" -type f -name '*.pkg.tar*' \
            -exec pacman --query --file '{}' \+ \
        | cut --delimiter ' ' --fields 2 | cut --delimiter '-' --fields 1 \
        | xargs | tr ' ' '|' | xargs --no-run-if-empty -I '{}' echo '({})')"

    echo "$UPSTREAM_SOURCES" \
        | grep --invert-match --extended-regex "${KEPT_VERSIONS:-'()'}"
)

# This function returns the directories where yay builds packages.
#
# The filesystem has to be rescanned at various points in this script, as each
# step can potentially remove any of such directories
yay_build_dirs() {
    echo "$YAY_CACHE_DIRS" \
        | xargs -I '{}' find '{}' -maxdepth 1 -mindepth 1 -type d
}

########################################
# Clean up pacman cache
########################################

# Remove uninstalled packages
paccache --quiet --remove --uninstalled --keep 0

# Remove old versions of installed packages, skipping ignored packages
grep --invert-match --extended-regex '^(#.*|\s*)$' \
    {{@@ pacman_ignore_path @@}} \
    | cut --delimiter '=' --fields 2 | xargs \
    | paccache --quiet --remove --ignore - --keep 1

########################################
# Clean up yay cache
########################################

clean_uninstalled_aur_packages

# Remove old versions of pacman package tarballs from the yay cache
yay_build_dirs \
    | xargs -I '{}' paccache --quiet --cachedir '{}' --remove --keep 3

# Remove unnecessary cache files from bin AUR packages from the yay cache
yay_build_dirs | grep --basic-regexp '.*-bin$' \
    | while read -r PACKAGE_DIR; do
        get_old_upstream_sources_and_build "$PACKAGE_DIR" \
            | xargs --no-run-if-empty rm --force --recursive
    done

# Remove unnecessary cache files from AUR source packages from the yay cache
yay_build_dirs | grep --basic-regexp --invert-match '.*-bin$' \
    | grep --basic-regexp --invert-match '.*-git$' \
    | while read -r PACKAGE_DIR; do
        # Remove upstream source tarballs. Actual source files and build
        # output are kept, as they belong to the latest version
        get_old_upstream_sources_and_build "$PACKAGE_DIR" \
            | xargs --no-run-if-empty file \
            | grep --perl-regex --word-regexp '(compressed|archive)' \
            | cut --delimiter ':' --fields 1 \
            | xargs --no-run-if-empty rm --force --recursive
    done
