#!/usr/bin/env sh

# This script compiles and sets up some blocks from i3blocks-contrib. It's
# meant to be used as an executable in a pacman hook

########################################
# arch-update
########################################

which yay | xargs -I '{}' ln -sf '{}' /usr/local/bin/yaourt

########################################
# cpu_usage2
########################################

make -C /usr/lib/i3blocks/cpu_usage2
