#!/usr/bin/env sh

# This script installs rust toolchains via rustup

########################################
# Ensure rustup paths exist
########################################

mkdir --parents "{{@@ rustup_home @@}}"

########################################
# Install rust toolchain
########################################

# rust-src is used by static analyzers
env RUSTUP_HOME="{{@@ rustup_home @@}}" \
    rustup toolchain install stable --component rust-src
