#!/usr/bin/env sh

# This script enables the NordVPN systemd service and makes it accessible
# to non-root users. It's meant to be used as an executable in a pacman hook

########################################
# Enabling NordVPN systemd service
########################################

systemctl enable --now nordvpnd

########################################
# Creating nordvpn group
########################################

groupadd --force nordvpn
