#!/usr/bin/env sh

# This script installs asdf version manager to a system location. It is meant
# to be used via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - STDIN: The GitHub release JSON metadata
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"

########################################
# Variables
########################################

INSTALL_DIR='/usr/local/bin'
EXEC_PATH="$INSTALL_DIR/asdf"

########################################
# Input processing
########################################

GITHUB_REPO="$1"

########################################
# Main
########################################

log_debug 'Download and install asdf version manager...'
# asdf is not available on ARMv7
download_github_release_asset '.name | endswith("linux-amd64.tar.gz")' \
        "$GITHUB_REPO" \
    | tar --extract --gzip --directory "$INSTALL_DIR"

log_debug "Set executable permissions to $EXEC_PATH..."
chmod +x "$EXEC_PATH"
