#!/usr/bin/env sh

# This script contains utility functions for dpkg hooks

# This function recursively computes the PID of the closest APT ancestor
# of a given process.
#
# Arguments:
#   - $1: The PID of the process whose closes APT ancestor PID is returned.
#         Optional, defaults to the current process' parent PID.
find_apt_ancestor_pid() (
    THIS_PID="${1:-$PPID}"

    if [ -z "$THIS_PID" ]; then
        echo >&2 "find_apt_ancestor_pid: empty PID."
        return 64
    elif [ "$THIS_PID" -eq 1 ]; then
        echo >&2 "find_apt_ancestor_pid: no APT ancestor found."
        return 63
    fi

    case "$(cat "/proc/$THIS_PID/comm")" in
        'apt'|'apt-get')
            echo "$THIS_PID"
            ;;

        *)
            find_apt_ancestor_pid "$(ps --pid "$THIS_PID" -o 'ppid:1=')"
            ;;
    esac
)

# This function returns the operation command line arguments of the first apt
# parent process
#
# Arguments:
#   - $1: The APT PID that triggered the current hook
apt_operation() {
    tr '\0' ' ' < "/proc/$1/cmdline" | cut --delimiter ' ' --fields 2
}

# This function returns the command line arguments of the first apt parent
# process that possibly contain package names.
#
# Arguments:
#   - $1: The APT PID that triggered the current hook
apt_packages() {
    tr '\0' ' ' < "/proc/$1/cmdline" | cut --delimiter ' ' --fields 3-
}
