#!/usr/bin/env sh

# This script is meant to execute actions before specific packages are
# uninstalled via APT.
#
# {{@@ header() @@}}

# This doesn't work if the script is sourced
. "$(dirname "$0")/lib"

########################################
# Setup logging
########################################

. "{{@@ logger_path @@}}"
logging_set_level 'info'
logging_set_journald 'off'
logging_set_tag 'on'

#######################################
# Functions
#######################################

# This function removes an alternative from the Debian alternative system.
#
# Arguments:
#   - $1: The name of the binary to add to the alternatives system
#   - $2: The alternatives group name
rm_alternative() {
    RM_ALT_BIN_NAME="$1"
    RM_ALT_GROUP_NAME="$2"

    # If the executable is not found on PATH, there's nothing to setup yet.
    # This script is executed multiple times by dpkg, not all of them have the
    # package fully unpacked on the system.
    RM_ALT_BIN_PATH="$(which "$RM_ALT_BIN_NAME")" || return 0

    log_info "Remove '$RM_ALT_BIN_NAME' from '$RM_ALT_GROUP_NAME' alternatives"
    update-alternatives --remove "$RM_ALT_GROUP_NAME" "$RM_ALT_BIN_PATH"

    unset RM_ALT_GROUP_NAME RM_ALT_BIN_NAME RM_ALT_BIN_PATH
}

########################################
# Main
########################################

case "$(apt_operation)" in
    'autopurge'|'autoremove'|'purge'|'remove')
        for PACKAGE in $(apt_packages); do
            case "$PACKAGE" in
                *bat*)
                    rm_alternative 'batcat' 'bat'
                    ;;

                *code-insiders*)
                    rm_alternative 'code-insiders' 'code'
                    ;;

                *docker-compose-plugin*)
                    log_info 'Disable podman daemon socket'
                    systemctl disable podman.socket
                    ;;

                *firefox-beta*)
                    rm_alternative 'firefox-beta' 'firefox'
                    ;;

                *podman-compose*)
                    log_info 'Remove "docker-compose" alias as "podman-compose"'
                    rm --force /usr/local/bin/docker-compose
                    ;;

                *rustup*)
                    log_info 'Remove all rust toolchains'
                    rm --force --recursive '{{@@ rustup_home @@}}'
                    ;;
            esac
        done
        ;;
esac
