#!/usr/bin/env sh

# This script installs i3-volume to a system location. It is meant to be used
# via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - $2: The GitHub release tag containing the artifacts to install
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"


########################################
# Variables
########################################

DST_DIR='/usr/local/bin'
SRC_EXEC='volume'

########################################
# Input processing
########################################

GITHUB_REPO="$1"
RELEASE_TAG="$2"

########################################
# Main
########################################

log_debug 'Download and install i3-volume...'
gh --repo "$GITHUB_REPO" release download "$RELEASE_TAG" --archive 'tar.gz' \
        --output - \
    | tar --extract --gzip --directory "$DST_DIR" --strip-components 1 \
        --wildcards "*/$SRC_EXEC"
chmod +x "$DST_DIR/$SRC_EXEC"
