#!/usr/bin/env bash

# This script is a convenience wrapper for dotdrop. It can be executed from
# any dorectory, and will run the dotdrop command for user/root, or for both.
#
# Arguments:
#   - --user USER: the user dotdrop will be executed for. Can be one of 'user',
#       'root' or 'both'. Optional, defaults to 'user' for unprivileged users
#        and to 'root' for root.
#   - $@: dotdrop arguments.
#
# Environment:
#   - $DOTFILES_HOME: the directory where Pipfile and dotdrop.sh are located.
#                     Defaults to $HOME/Files/Programming/sys/dotfiles.

#######################################
# Variables
#######################################

DOTFILES_HOME="${DOTFILES_HOME:-$HOME/Files/Programming/sys/dotfiles}"

#######################################
# Input processing
#######################################

WHO=''
CMD=''
ARGS=()

CURR_ARG=''
for ARG in "$@"; do
    case "$CURR_ARG" in
        'user')
            WHO="$ARG"
            CURR_ARG=''
            continue
            ;;
    esac
    case "$ARG" in
        '--user'|'-U')
            CURR_ARG='user'
            ;;
        *)
            # Accorting to dotdrop syntax, the first argument must be the
            # command.
            [ -z "$CMD" ] && {
                CMD="$ARG"
                continue
            }

            # Relative paths need to be resolved before cd-ing into
            # $DOTFILES_HOME, otherwise they become afterwards
            [ -e "$ARG" ] && ARG="$(readlink -f "$ARG")"
            ARGS+=("$ARG")
            ;;
    esac
done

case "$WHO" in
    user|root|both)
        ;;
    '')
        [ "$USER" = 'root' ] && WHO='root' || WHO='user'
        ;;
    *)
        echo >&2 "Error: '$WHO' user given. Muse be one of 'user', 'root' or" \
            "'both'"
        exit 1
        ;;
esac

#######################################
# Executing dotdrop
#######################################

# Will exit the exript if $DOTFILES_HOME is not defined and
# $HOME/Files/Programming/sys/dotfiles doesn't exist
cd $DOTFILES_HOME || exit

case "$WHO" in
    user|both)
        pipenv run bash dotdrop.sh "$CMD" -c 'config-user.yaml' "${ARGS[@]}"
        ;;
esac

case "$WHO" in
    root|both)
        if [ "$USER" = 'root' ]; then
            pipenv run bash dotdrop.sh "$CMD" -c 'config-root.yaml' \
                "${ARGS[@]}"
        else
            sudo pipenv run bash dotdrop.sh "$CMD" -c 'config-root.yaml' \
                "${ARGS[@]}"
        fi
        ;;
esac

cd - &> /dev/null || exit
