--[[

Find and replace macro, generated by new-macro.lua
plugin.

--]]

-- Getting all document content

local doc = geany.text()

--[[

Begin of replacement section

--]]

doc = doc:gsub('local mw = require%([\'"]mw[\'"]%)\n+', '')
doc = doc:gsub([[require%((['"])(.-)['"]%)]], function(quotes, module)
	return table.concat{'require(', quotes, 'Modulo:',
			module:gsub('%-', '/'), quotes, ')'}
end)
doc = doc:gsub('require%("(.-)"%)', "mw.loadData('%1')")
doc = doc:gsub('Modulo:Modulo:', 'Modulo:')

--[[

End of replacement section

--]]

-- Changing document content to replaced one

geany.text(doc)
