#!/usr/bin/env sh

# This script installs i3-volume to a system location. It is meant to be used
# via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - STDIN: The GitHub release JSON metadata
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"


########################################
# Variables
########################################

SRC_EXEC_NAME='volume'

########################################
# Functions
########################################

# This function cleans up after the script. It is mean to be used as a trap
cleanup() {
    log_debug 'Clean up'
    rm --force --recursive "$TMP_SRC_EXTRACT_DIR"
    trap - EXIT
    exit
}

########################################
# Input processing
########################################

GITHUB_REPO="$1"

########################################
# Main
########################################

trap cleanup EXIT INT HUP

TMP_SRC_EXTRACT_DIR="$(mktemp --tmpdir --directory XXX.i3-volume)"

log_debug 'Download i3-volume...'
download_from_source_tarball "$SRC_EXEC_NAME" "$GITHUB_REPO" \
    "$TMP_SRC_EXTRACT_DIR"

log_debug 'Install i3-volume'
install --mode 755 "$TMP_SRC_EXTRACT_DIR/$SRC_EXEC_NAME" /usr/local/bin
