#!/usr/bin/env sh

# This script installs Bitwarden to a system location. It is meant to be used
# via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - STDIN: The GitHub release JSON metadata
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"

########################################
# Input processing
########################################

GITHUB_REPO="$1"

########################################
# Main
########################################

# Bitwarden is not available on ARMv7
install_github_release_deb 'endswith("amd64.deb")' "$GITHUB_REPO"
