#!/usr/bin/env sh

# {{@@ header() @@}}
#
# This script initializes the X11 session.

#######################################
# Display-specific environment setup
#######################################

autorandr --change --force
