#!/usr/bin/env sh

# This script initializes the X11 session.
#
# {{@@ header() @@}}

#######################################
# Display-specific environment setup
#######################################

autorandr --change --force
