language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
dist: focal
install:
  - "pip install pip --upgrade"
  - "pip install -r tests-requirements.txt"
  - "pip install -r requirements.txt"
  - "npm install -g remark-cli remark-validate-links"
  - "npm install -g markdown-link-check"
script:
  ./tests.sh
after_success:
  coveralls
env:
  global:
    - DOTDROP_FORCE_NODEBUG=
    - DOTDROP_NOBANNER=
