#!/usr/bin/env sh

# This script installs devbox to a system location. It is meant to be used via
# the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - STDIN: The the GitHub release JSON metadata
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"

########################################
# Variables
########################################

INSTALL_DIR='/usr/local/bin'

########################################
# Input processing
########################################

GITHUB_REPO="$1"

########################################
# Main
########################################

log_debug 'Download and extract devbox to temporary directory...'

TMP_DIR="$(mktemp --directory --tmpdir gh-release-devbox.XXX)"
# shellcheck disable=SC2064
trap "cleanup_trap $TMP_DIR" EXIT INT HUP TERM

ASSET_JQ_FILTER="$(uname --machine \
    | sed 's/x86_64/amd64/g' \
    | xargs printf '(.content_type == "application/gzip") and
        (.name | contains("%s") and contains("linux"))')"

download_github_release_asset "$ASSET_JQ_FILTER" "$GITHUB_REPO" \
    | tar --extract --gzip --directory "$TMP_DIR"

log_debug "Install devbox executables to $INSTALL_DIR..."
install --mode 755 "$TMP_DIR/"* "$INSTALL_DIR"
