#!/usr/bin/env sh

# This script installs antibody to a system location. It is meant to be used
# via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - STDIN: The GitHub release JSON metadata
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"

########################################
# Functions
########################################

# This function cleans up after the script. It is mean to be used as a trap
cleanup() {
    log_debug 'Clean up'
    rm --force "$TMP_DEB_FILE"
    trap - EXIT
    exit
}

########################################
# Input processing
########################################

GITHUB_REPO="$1"

########################################
# Main
########################################

trap cleanup EXIT INT HUP

TMP_DEB_FILE="$(mktemp 'XXX-antibody.deb')"

log_debug 'Download antibody...'
download_github_release_asset '.name | endswith("linux_amd64.deb")' \
    "$GITHUB_REPO" "$TMP_DEB_FILE"

log_debug 'Install antibody...'
dpkg --install "$TMP_DEB_FILE" | log_debug
