#!/usr/bin/env sh

# This script installs antibody to a system location. It is meant to be used
# via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - STDIN: The GitHub release JSON metadata
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"

########################################
# Input processing
########################################

GITHUB_REPO="$1"

########################################
# Main
########################################

log_debug 'Determine antibody deb package suffix...'
case "$(uname --machine)" in
    'x86_64')
        DEB_JQ_FILTER='endswith("linux_amd64.deb")'
        ;;

    'armv7l')
        DEB_JQ_FILTER='endswith("linux_armv7.deb")'
        ;;

    *)
        echo >&2 "Unknown machine hardware name"
        exit 127
        ;;
esac

install_github_release_deb "$DEB_JQ_FILTER" "$GITHUB_REPO"
