#!/usr/bin/env sh

# This script initializes the POSIX shell

# {{@@ header() @@}}

#######################################
# Loading configuration paths
#######################################

# shellcheck disable=2027,2140
. "{{@@ dotdirs_file | home_abs2var @@}}"

#######################################
# Loading environment variables
#######################################

. "$SDOTDIR/shenv"

#######################################
# Loading aliases
#######################################

. "$SDOTDIR/aliases.sh"

#######################################
# Loading functions
#######################################

. "$SDOTDIR/functions.sh"

{%@@ if user == 'user' -@@%}

########################################
# Console login
########################################

start_graphical_session

{%@@ endif -@@%}

########################################
# Loading interactive setup
########################################

case "$-" in
    *i*)
        . "$SDOTDIR/interactive/init.sh"
        ;;
esac
