#!/usr/bin/env sh

# This script initializes the POSIX shell

# {{@@ header() @@}}

#######################################
# Loading configuration paths
#######################################

# shellcheck disable=2027,2140
. "{{@@ shell_dirs_file | home_abs2var @@}}"

#######################################
# Loading environment variables
#######################################

. "$SDOTDIR/shenv"

#######################################
# Loading aliases
#######################################

. "$SDOTDIR/aliases.sh"

#######################################
# Loading functions
#######################################

. "$SDOTDIR/functions.sh"

########################################
# Loading interactive setup
########################################

case "$-" in
    *i*)
        . "$SDOTDIR/interactive/init.sh"
        {%@@ if user == 'user' and distro_id == 'arch'
            and not is_headless | is_truthy @@%}

        ########################################
        # Console login
        ########################################

        start_graphical_session

        {%@@ endif @@%}
        ;;
esac
