#!/usr/bin/env sh

# {{@@ header() @@}}

# This script defines environment variables for POSIX shell

#######################################
# Custom
#######################################

export DOTFILES_HOME="{{@@ dotfiles_home | find_in_home | home_abs2var @@}}"

{%@@ if exists(docker_path) @@%}
#######################################
# Docker
#######################################

export DOCKER_CONFIG="{{@@ docker_path | home_abs2var @@}}"

{%@@ endif @@%}
#######################################
# Path
#######################################

LOCAL_PATH='/usr/local/bin'
case "$PATH" in
    *$LOCAL_PATH*)
        ;;
    *)
        export PATH="$LOCAL_PATH:$PATH"
        ;;
esac

{%@@ if user == 'root' @@%}
LOCAL_PATH='/usr/local/sbin'
case "$PATH" in
    *$LOCAL_PATH*)
        ;;
    *)
        export PATH="$LOCAL_PATH:$PATH"
        ;;
esac
{%@@ endif @@%}

unset LOCAL_PATH
