#!/usr/bin/env sh

# This script defines environment variables for POSIX shell

# {{@@ header() @@}}

#######################################
# Loading configuration paths
#######################################

# shellcheck disable=2027,2140
. "{{@@ shell_dirs_file | home_abs2var @@}}"

########################################
# Bash
########################################

# This variable defines the script to be sourced for bash non-interactive
# shells. Since it needs to be defined *before* the bash non-interactive shell
# is created, it is defined here for all POSIX-compliant shell.
export BASH_ENV="$BDOTDIR/bashenv"

{%@@ if is_headless | is_truthy -@@%}

########################################
# GnuPG agent
########################################

# This variable is needed by GnuPG agent's headless pinentry.
if [ -z "$GPG_TTY" ]; then
    export GPG_TTY="$(tty)"

    # Inform gpg-agent that GPG_TTY has changed
    gpg-connect-agent updatestartuptty /bye > /dev/null
fi

{%@@ endif -@@%}

########################################
# History
########################################

# This variable lists the commands that shouldn't enter the shell history
export HIST_IGNORED_CMDS='cd|cd -|clear|exit|l|root|t'

# This variable lists the git commands that shouldn't enter the shell history
export HIST_IGNORED_GIT='git ap|git c|git g|git i'

# This variable lists my common typos that shouldn't enter the shell history
export HIST_IGNORED_TYPOS='gi t*|gl'

{#@@ Arch's package places rustup and its shims already on PATH :D @@#}
{%@@ if env['HOST'] != 'work' and 'arch' not in distro_id -@@%}

#######################################
# rustup
#######################################

. "$RUSTUP_SHIMS/env"

{%@@ endif -@@%}

#######################################
# Path
#######################################

# Local paths are moved to the beginning of PATH because local binaries are
# often shims. Hence they need to be first on PATH.

{%@@ set local_path = [
        '/usr/local/sbin' if user == 'root' else None,
        '/usr/local/bin',
        asdf_data + '/shims'
    ] | select | join(':') -@@%}

LOCAL_PATH="{{@@ local_path @@}}"
PATH_WITHOUT_LOCAL="$(echo "$PATH" \
    | sed "s|$LOCAL_PATH||g; s|^:||g; s|:\+|:|g")"
export PATH="${LOCAL_PATH:?}:${PATH_WITHOUT_LOCAL:?}"

unset LOCAL_PATH PATH_WITHOUT_LOCAL
