#!/usr/bin/env sh

# This script defines environment variables for POSIX shell

# {{@@ header() @@}}

#######################################
# Loading configuration paths
#######################################

# shellcheck disable=2027,2140
. "{{@@ dotdirs_file | home_abs2var @@}}"

########################################
# Bash
########################################

# This variable defines the script to be sourced for bash non-interactive
# shells. Since it needs to be defined *before* the bash non-interactive shell
# is created, it is defined here for all POSIX-compliant shell.
export BASH_ENV="$BDOTDIR/bashenv"

{%@@ if is_headless | is_truthy -@@%}

########################################
# GnuPG agent
########################################

# This variable needs to be set in order for GnuPG agent's headless pinentry to
# work. It can't be set in .pam_environment because it is initialized by a
# shell command
export GPG_TTY="$(tty)"

{%@@ endif -@@%}

########################################
# History
########################################

# This variable lists the commands that shouldn't enter the shell history
export HIST_IGNORED_CMDS='cd|cd -|clear|exit|l|root|t'

# This variable lists the git commands that shouldn't enter the shell history
export HIST_IGNORED_GIT='git ap|git c|git g|git i'

# This variable lists my common typos that shouldn't enter the shell history
export HIST_IGNORED_TYPOS='gi t*|gl'

#######################################
# Path
#######################################

LOCAL_PATH='/usr/local/bin'
case "$PATH" in
    *$LOCAL_PATH*)
        ;;
    *)
        export PATH="$LOCAL_PATH:$PATH"
        ;;
esac

{%@@ if user == 'root' -@@%}

LOCAL_PATH='/usr/local/sbin'
case "$PATH" in
    *$LOCAL_PATH*)
        ;;
    *)
        export PATH="$LOCAL_PATH:$PATH"
        ;;
esac

{%@@ endif -@@%}

unset LOCAL_PATH
