#!/usr/bin/env sh

# This script installs antibody to a system location. It is meant to be used
# via the gh-release command, as it reads GitHub release assets metadata in
# JSON format from stdin.
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ logger_path @@}}"

########################################
# Functions
########################################

# This function cleans up after the script. It is mean to be used as a trap
cleanup() {
    log_debug 'Clean up'
    rm --force "$TMP_DEB_FILE"
    trap - EXIT
    exit
}

########################################
# Main
########################################

trap cleanup EXIT INT HUP

TMP_DEB_FILE="$(mktemp 'XXX-antibody.deb')"

log_debug 'Download antibody...'
jq --raw-output '.[] | select(.name | contains("linux_amd64.deb")).browser_download_url' \
    | xargs wget --quiet --output-document "$TMP_DEB_FILE"

log_debug 'Install antibody...'
dpkg --install "$TMP_DEB_FILE" | log_debug
