#!/usr/bin/env bash

# Xfce session initialization script

# Invoking the default initialization
[ -f /etc/xdg/xfce4/xinitrc ] && . /etc/xdg/xfce4/xinitrc

# Setting up UI scaling
exec 1>/home/maze/log.init
SCALING=$(which adjust-scaling)
[ -f "$SCALING" ] && . "$SCALING"

