#!/usr/bin/env bash

# This script is a convenience wrapper for dotdrop. It can be executed from
# any dorectory, and will run the dotdrop command for user/root, or for both.

#######################################
# Variables
#######################################

DOTFILES_HOME="${DOTFILES_HOME:-$HOME/Files/Programming/sys/dotfiles}"

#######################################
# Input processing
#######################################

WHO="$1"
CMD="$2"
shift 2

#######################################
# Executing dotdrop
#######################################

# Will exit the exript if $DOTFILES_HOME is not defined and
# $HOME/Files/Programming/sys/dotfiles doesn't exist
cd $DOTFILES_HOME || exit

case "$WHO" in
    user|both)
        pipenv run bash dotdrop.sh "$CMD" -c 'config-user.yaml' "$@"
        ;;
esac

case "$WHO" in
    root|both)
        sudo pipenv run bash dotdrop.sh "$CMD" -c 'config-root.yaml' "$@"
        ;;
esac

cd - &> /dev/null || exit
