#!/usr/bin/env bash

# This script is a convenience wrapper for dotdrop. It can be executed from
# any dorectory, and will run the dotdrop command for user/root, or for both.

#######################################
# Variables
#######################################

DOTFILES_HOME="${DOTFILES_HOME:-$HOME/Files/Programming/sys/dotfiles}"
export DOTDROP_ACTIONS_PATH="${DOTDROP_ACTIONS_PATH\
:-$HOME/Files/Programming/bash/setup-scripts\/dotdrop-actions}"

#######################################
# Input processing
#######################################

WHO="$1"
CMD="$2"
shift 2

#######################################
# Executing dotdrop
#######################################

cd $DOTFILES_HOME || exit

if [ "$WHO" = 'both' ]; then
    pipenv run bash dotdrop.sh "$CMD" -c 'config-user.yaml' "$@"
    sudo DOTDROP_ACTIONS_PATH="$DOTDROP_ACTIONS_PATH" \
        pipenv run bash dotdrop.sh "$CMD" -c 'config-root.yaml' "$@"
else
    pipenv run bash dotdrop.sh "$CMD" -c "config-$WHO.yaml" "$@"
fi

cd - &> /dev/null || exit
