# This is the resolution of my work desktop. Added manually as VMware doesn't
# recognize it automatically, possibly due to display scaling on the host.

Section "Monitor"
    Identifier "Monitor0"
    # Generated via `cvt 3840 2160 60 | tail -n 1`
    Modeline "3840x2160"  712.75  3840 4152 4576 5312  2160 2163 2168 2237 -hsync +vsync
    Option "PreferredMode" "3840x2160"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Virtual1"
    Monitor "Monitor0"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "3840x2160"
    EndSubSection
EndSection
