#!/usr/bin/env sh

# This script installs Docker credentials SecretService to a system location.
# It is meant to be used via the gh-release command.
#
# Arguments:
#   - $1: The GitHub repository name the software is installed from
#   - $2: The GitHub release tag containing the artifacts to install
#
# {{@@ header() @@}}

set -e

#######################################
# Libraries includes
#######################################

. "{{@@ gh_release_path @@}}"

########################################
# Variables
########################################

EXEC_PATH='/usr/local/bin/docker-credential-secretservice'

########################################
# Input processing
########################################

GITHUB_REPO="$1"

########################################
# Main
########################################

log_debug 'Download and install Docker credentials SecretService...'
cpu_arch 'amd64' | xargs -I '{}' gh --repo "$GITHUB_REPO" release download \
    "$RELEASE_TAG" --output - --pattern '*secretservice*linux*{}' \
        > "$EXEC_PATH"
chmod +x "$EXEC_PATH"
